# Generated by Django 4.2.4 on 2023-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="file_name",
            field=models.FileField(null=True, unique=True, upload_to="output/%Y/%m/%d"),
        ),
    ]
