# Generated by Django 4.2.4 on 2023-09-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='analysis_tech',
        ),
    ]
