# Generated by Django 4.2.4 on 2023-09-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0002_alter_output_file_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="output",
            old_name="describe",
            new_name="path",
        ),
        migrations.RemoveField(
            model_name="output",
            name="file_name",
        ),
    ]
