# Generated by Django 4.2.4 on 2023-10-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0004_alter_output_raw_data_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="path",
            field=models.FileField(
                null=True, unique=True, upload_to="analyze/%Y/%m/%d"
            ),
        ),
    ]
